CREATE USER panther PASSWORD 'panther';
CREATE DATABASE panther;
GRANT ALL PRIVILEGES ON DATABASE panther TO panther;

CREATE USER nss PASSWORD 'nss';
CREATE DATABASE nss;
GRANT ALL PRIVILEGES ON DATABASE nss TO nss;

CREATE USER vince PASSWORD 'vince';
CREATE DATABASE vince;

GRANT ALL PRIVILEGES ON DATABASE vince TO vince;
GRANT ALL PRIVILEGES ON DATABASE panther TO vince;
GRANT ALL PRIVILEGES ON DATABASE nss TO vince;